### PR TITLE
Add custom output format support in manipulator (fm query param)

### PR DESCRIPTION
**Pull request by albertusangga**
With this PR we can serve image in different format than the original file

### CODE REVIEW

**Comment by adalberht** [comment]
@ajatprabha  agreed, revised with the latest diff

**Comment by baskarap** [comment]
Is it ok if we rebase this after the webp work gets merged to master? Sorry for the inconvenience.

**Comment by ajatprabha** [comment]
@adalberht Can you update this, since now WebP support PR is merged?

**Comment by adalberht** [comment]
@ajatprabha which parts need to be updated? I think this PR also already supports outputing to WebP also

**Comment by ajatprabha** [comment]
@adalberht Okay, can we merge this then?

**Comment by ajatprabha** [comment]
What's the status of this PR? Should we merge this?
CC: @albertusangga @baskarap

**Comment by albertusangga** [comment]
To be frank I've forgotten what was the usecase for this PR.
I guess I just wanted to add new functionality to Darkroom.
Since I also almost forgot the code and how to rebase it, I'm closing this PR.
Let me know if you want to reopen this @baskarap @ajatprabha

**Pull request closed without merging**
